services:
  - type: web
    name: afritravel
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn blog_voyages.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: blog_voyages.settings
      - key: SECRET_KEY
        value: remplis-moi-avec-un-vrai-secret
      - key: DEBUG
        value: False
